Repository wikimedia/restbase, pull requests merged in 2018-08, with the labels that each got.

#1040 Mathoid: Tests: Ensure all return formats are tested
  test/features/mathoid.js
Labels: hygiene, tests

#1039 Delete revisions on a new render creation
  sys/multi_content_bucket.js
Labels: enhancement

#1042 Fallback to wiki default language if page_lang is not set
  lib/mwUtil.js
Labels: enhancement

#1044 Remove jshint and jscs in favor of eslint
  .jscs.json
  .jshintignore
  .jshintrc
  package.json
  test/index.js
Labels: hygiene, tests

#1047 Added rvslots=main to the MW API revision request.
  sys/page_revisions.js
  test/features/errors/invalid_request.js
  test/features/pagecontent/access_checks.js
  test/features/pagecontent/save_api.js
Labels: hygiene, technical debt

#1053 Bump expected Parsoid version to 1.7.0
  test/features/parsoid/transform.js
  v1/content.yaml
  v1/transform.yaml
Labels: API
