Repository wikimedia/restbase, pull requests merged in 2018-07, with the labels that each got.

#1013 Update the related endpoint spec
  v1/related.yaml
Labels: API, hygiene

#983 API: Include anchors in redirect targets
  lib/mwUtil.js
  sys/parsoid.js
  test/features/pagecontent/redirects.js
Labels: API, bug

#1015 Release v0.19.0
  package.json
Labels: dependency update, release

#1018 Hygiene: Always use https for wikimedia/wmflabs URLs in example configs
  config.example.wikimedia.yaml
  config.example.yaml
Labels: hygiene, tests

#1022 Minor DRY fix: use _hydrateResponse from superclass in feed.js
  v1/feed.js
Labels: hygiene

#1023 Expose Javascript endpoint
  projects/dev.yaml
  projects/wmf_default.yaml
  projects/wmf_enwiki.yaml
  projects/wmf_wiktionary.yaml
  v1/javascript.yaml
Labels: API

#1025 Release v0.19.1
  package.json
Labels: release

#1026 Fixed view history merging for cases with missing dates
  v1/feed.js
Labels: bug

#1027 Transform end points: Raise limit to 25 rps
  v1/transform.yaml
Labels: API, hygiene

#1028 mobile-html: Do not anchor the ETag field in x-amples
  v1/mobile-html.yaml
Labels: API, hygiene, tests

#1029 recommendation API: fix typo in content-type
  v1/recommend.yaml
Labels: API, technical debt

#1031 Release v0.19.2
  package.json
Labels: release

#1032 Update references spec
  v1/references.yaml
Labels: API, hygiene
