Repository wikimedia/restbase, pull requests merged in 2018-09, with the labels that each got.

#1059 Do not emit the dependency update event for non-latest rerenders.
  sys/parsoid.js
Labels: enhancement, hygiene

#1060 Remove restrictions table
  lib/access_check_filter.js
  lib/mwUtil.js
  lib/revision_table_access_check_filter.js
  sys/page_revisions.js
  sys/page_revisions.yaml
  sys/parsoid.js
  test/features/pagecontent/access_checks.js
  v1/content.yaml
  v1/definition.yaml
  v1/media.yaml
  v1/metadata.yaml
  v1/mobile-html.yaml
  v1/mobileapps.yaml
  v1/pdf.yaml
  v1/references.yaml
  v1/summary.yaml
  v1/summary_new.yaml
Labels: hygiene, technical debt

#1061 Revert "Revert bumping Parsoid content-type filter"
  v1/content.yaml
  v1/transform.yaml
Labels: technical debt

#1063 key_rev_value: Return the stored headers, if any
  sys/key_rev_value.js
  test/features/buckets/revisioned_bucket.js
Labels: bug

#1064 MCS: Remove tests that directly call the service
  v1/availability.yaml
  v1/css.yaml
  v1/javascript.yaml
  v1/media.yaml
  v1/metadata.yaml
  v1/mobile-html.yaml
  v1/random.yaml
  v1/references.yaml
Labels: API, tests

#1066 Do not dynamically generate Parsoid content if TID is provided.
  sys/parsoid.js
  test/features/parsoid/ondemand/ondemand.js
  test/features/parsoid/transform.js
Labels: bug

#1068 Add more logging in metrics temporarily for content-negotiation
  lib/content_negotiation_filter.js
Labels: enhancement

#1069 Don't try upgrading if .minor version is satisfied ok
  lib/content_negotiation_filter.js
Labels: bug
