Repository wikimedia/restbase, pull requests merged in 2018-06, with the labels that each got.

#999 Tests: Fix the transform end point expected outcome
  test/features/parsoid/transform.js
  v1/transform.yaml
Labels: technical debt, tests

#1000 Update required media item fields
  v1/media.yaml
Labels: API, technical debt, tests

#1002 Fix: Remove 'original' from required props in media_item defn
  v1/media.yaml
Labels: API, technical debt

#1004 Include `page_language` into the title_revision table.
  sys/page_revisions.js
  v1/content.yaml
Labels: API, new feature

#1006 Bump rb-mod-table-cassandra to v1.0.1
  package.json
Labels: dependency update
