Repository wikimedia/restbase, pull requests merged in 2018-04, with the labels that each got.

#981 Respect the content-type returned by the service
  v1/definition.yaml
Labels: API, bug

#982 Release v0.18.1
  package.json
Labels: release

#984 Pageviews: Use `keep-alive` for AQS connections
  v1/metrics.yaml
Labels: API, enhancement

#980 Expose CSS endpoints
  projects/dev.yaml
  projects/wmf_default.yaml
  projects/wmf_enwiki.yaml
  projects/wmf_wiktionary.yaml
  test/features/css.js
  v1/css.yaml
Labels: API, enhancement

#988 Minor: Remove unneeded CSS test file
  test/features/css.js
Labels: hygiene
