Repository wikimedia/restbase, pull requests merged in 2018-03, with the labels that each got.

#966 Enable the content-type filter for summary
  v1/summary_new.yaml
Labels: API, enhancement

#970 Remove obsolete swagger-test tests
  package.json
  test/features/specification/swagger.js
  test/features/specification/swagger.yaml
Labels: hygiene, tests

#969 Run tests with SQLite by default
  config.test.yaml
  test/utils/run_tests.sh
  test/utils/server.js
Labels: tests

#968 Add PCS /page/media endpoint
  projects/dev.yaml
  projects/wmf_default.yaml
  projects/wmf_enwiki.yaml
  projects/wmf_wiktionary.yaml
  test/features/media.js
  test/features/pagecontent/access_checks.js
  v1/media.yaml
  v1/mobileapps.yaml
Labels: API, new feature

#971 Change the purged_cache_control in example config to match production
  config.example.wikimedia.yaml
Labels: hygiene

#972 Add notloggedin to list of known errors
  sys/action.js
Labels: hygiene

#975 Lists API: Minor: Fix param type in getContinueFrom()
  v1/lists.js
Labels: technical debt

#976 Allow specifying expected content type in the ensure_content_type filter
  lib/ensure_content_type.js
Labels: enhancement

#977 Add tag descriptions for citations and recommendations
  v1/citoid.yaml
  v1/recommend.yaml
Labels: API, hygiene
