Repository wikimedia/restbase, pull requests merged in 2018-05, with the labels that each got.

#992 Correctly indent http filer allow options
  config.example.yaml
Labels: hygiene, technical debt

#994 Remove attempting to renew the TTL
  sys/parsoid.js
Labels: hygiene, technical debt

#995 Stabilize tests that depend on content being present
  config.test.yaml
Labels: hygiene, tests

#996 Remove useless double-checking of the stored content
  sys/parsoid.js
Labels: hygiene, technical debt

#991 Adapted to the new hyper.logger exposure
  lib/ensure_content_type.js
  lib/normalize_title_filter.js
  package.json
  sys/action.js
  sys/events.js
  sys/key_rev_value.js
  sys/key_value.js
  sys/mathoid.js
  sys/multi_content_bucket.js
  sys/parsoid.js
  sys/table.js
  v1/lists.js
Labels: dependency update, enhancement, hygiene

#993 Transform: Update /list/{tool}/{/from}/{/to} end point
  v1/transform-global.yaml
Labels: API, enhancement

#997 Tests: Define the logger for the router
  package.json
  test/features/router/buildTree.js
Labels: dependency update, technical debt, tests
