Repository wikimedia/restbase, pull requests merged in 2019-03, with the labels that each got.

#1099 Update dependencies; release v0.19.3
  package.json
Labels: release

#1101 Improve test runner and use service-runner provided tests runner.
  .mocharc.yaml
  config.example.wikimedia.yaml
  config.test.yaml
  package.json
  test/features/buckets/key_value_bucket.js
  test/features/buckets/revisioned_bucket.js
  test/features/errors/invalid_request.js
  test/features/errors/notfound.js
  test/features/events/events.js
  test/features/feed.js
  test/features/lists.js
  test/features/mathoid.js
  test/features/media.js
  test/features/metadata.js
  test/features/metrics.js
  test/features/mobileapps.js
  test/features/pagecontent/access_checks.js
  test/features/pagecontent/content_negotiation.js
  test/features/pagecontent/language_variants.js
  test/features/pagecontent/pagecontent.js
  test/features/pagecontent/redirects.js
  test/features/pagecontent/rerendering.js
  test/features/pagecontent/revisions.js
  test/features/pagecontent/save_api.js
  test/features/parsoid/ondemand/ondemand.js
  test/features/parsoid/transform.js
  test/features/pdf.js
  test/features/post_data.js
  test/features/references.js
  test/features/router/buildTree.js
  test/features/router/handlerTemplate.js
  test/features/router/misc.js
  test/features/schema_tests.js
  test/features/security/security.js
  test/features/specification/monitoring.js
  test/mocha.opts
  test/utils/assert.js
  test/utils/link_creator.sh
  test/utils/logStream.js
  test/utils/server.js
  test/utils/uri_dump_filter.js
Labels: hygiene, tests

#1100 Update v1/ yaml to be swagger 2.0 compliant
  lib/base_feed.js
  package.json
  test/features/schema_tests.js
  v1/announcements.yaml
  v1/common_schemas.yaml
  v1/content.yaml
  v1/content_segments.yaml
  v1/css.yaml
  v1/feed.yaml
  v1/graphoid.yaml
  v1/javascript.yaml
  v1/lists.yaml
  v1/media.yaml
  v1/metadata.yaml
  v1/mobile-html.yaml
  v1/mobileapps.yaml
  v1/onthisday.yaml
  v1/pdf.yaml
  v1/recommend.yaml
  v1/references.yaml
  v1/summary.yaml
  v1/summary_new.yaml
  v1/transform-global.yaml
  v1/transform-lang.js
  v1/transform-lang.yaml
  v1/transform.yaml
  v1/trending.js
  v1/trending.yaml
Labels: API, enhancement, technical debt
