Repository wikimedia/restbase, pull requests merged in 2019-05, with the labels that each got.

#1129 Parsoid simplification, remove old stash
  sys/parsoid.js
Labels: enhancement, technical debt

#1130 Parsoid simplification. Remove sections API
  sys/parsoid.js
  test/features/pagecontent/pagecontent.js
  test/features/parsoid/ondemand/ondemand.js
  test/features/parsoid/transform.js
  v1/content.yaml
  v1/transform.yaml
Labels: API, technical debt

#1132 Parsoid simplifications. Do not frontent cache if stash was requested
  sys/parsoid.js
  test/features/pagecontent/pagecontent.js
  v1/content.yaml
Labels: new feature

#1133 Fix references in definitions endpoint docs.
  v1/definition.yaml
Labels: API, bug

#1131 Parsoid simplification. Switch latest bucket and provide fallback.
  .eslintrc.yml
  config.test.yaml
  sys/parsoid.js
  test/features/pagecontent/pagecontent.js
  test/features/pagecontent/rerendering.js
  test/features/parsoid/ondemand/ondemand.js
Labels: API, enhancement, hygiene, technical debt

#1134 Properly grab the content from the fallback bucket
  sys/parsoid.js
Labels: bug, technical debt

#1135 Don't provide original content to parsoid for wt2html transform.
  sys/parsoid.js
  test/features/parsoid/transform.js
Labels: API, bug

#1138 Temporary copy over the data from old buckets
  sys/parsoid.js
Labels: technical debt

#1139 Clone response before saving it to new bucket.
  package.json
  sys/parsoid.js
Labels: bug, technical debt

#1137 Remove fallback for stashed parsoid.
  doc/Implementation.md
  projects/dev.yaml
  projects/example.yaml
  projects/wikimedia.org.yaml
  projects/wmf_default.yaml
  projects/wmf_enwiki.yaml
  projects/wmf_wikidata.yaml
  projects/wmf_wikipedia.yaml
  projects/wmf_wikivoyage.yaml
  projects/wmf_wiktionary.yaml
  sys/key_rev_value.js
  sys/key_rev_value.yaml
  sys/multi_content_bucket.js
  sys/multi_content_bucket.yaml
  sys/parsoid.js
  test/features/buckets/revisioned_bucket.js
  test/test_module.yaml
Labels: API, hygiene, technical debt

#1140 Parsoid: Rate limit stashing requests
  config.example.wikimedia.yaml
  sys/parsoid.js
  v1/content.yaml
  v1/transform.yaml
Labels: API, config change, enhancement

#1120 Update specs to OpenAPI 3.0.1
  package.json
  projects/wmf_wiktionary.yaml
  sys/action.js
  sys/key_value.yaml
  sys/page_revisions.yaml
  sys/parsoid.yaml
  sys/post_data.yaml
  test/features/pagecontent/pagecontent.js
  test/features/schema_tests.js
  test/test_module.yaml
  v1/announcements.yaml
  v1/availability.yaml
  v1/citoid.yaml
  v1/common_schemas.yaml
  v1/content.yaml
  v1/content_segments.yaml
  v1/css.yaml
  v1/definition.yaml
  v1/feed.yaml
  v1/graphoid.yaml
  v1/javascript.yaml
  v1/lists.yaml
  v1/mathoid.yaml
  v1/media.yaml
  v1/metadata.yaml
  v1/metrics.yaml
  v1/mobile-html.yaml
  v1/mobileapps.yaml
  v1/onthisday.yaml
  v1/pdf.yaml
  v1/random.yaml
  v1/recommend.yaml
  v1/references.yaml
  v1/related.yaml
  v1/summary.yaml
  v1/summary_new.yaml
  v1/transform-global.yaml
  v1/transform-lang.yaml
  v1/transform.yaml
Labels: API, enhancement

#1136 Parsoid: Remove `/page/html/{title}/{revision}/{tid}`
  test/features/pagecontent/rerendering.js
  v1/content.yaml
Labels: API, hygiene

#1142 Hygene: Remove unused `extend` package
  package.json
Labels: hygiene, technical debt

#1143 Remove parsoid self-call to get a pagebundle.
  sys/parsoid.js
  sys/parsoid.yaml
Labels: hygiene, technical debt
