Repository wikimedia/restbase, pull requests merged in 2019-06, with the labels that each got.

#1150 Mathoid: Move resource declarations into the sys/ module
  sys/mathoid.js
  v1/mathoid.yaml
Labels: enhancement, technical debt

#1151 Rm backwards compatibility for mediawiki-basefields
  package.json
Labels: API, technical debt

#1152 Replace cassandra-uuid with uuid
  lib/base_feed.js
  lib/mwUtil.js
  lib/uuidUtils.js
  package.json
  sys/events.js
  sys/key_value.js
  sys/page_revisions.js
  sys/page_save.js
  sys/parsoid.js
  test/features/buckets/key_value_bucket.js
  test/features/events/events.js
  test/features/parsoid/ondemand/ondemand.js
  test/features/uuidutils.js
Labels: hygiene, technical debt

#1154 Add /page/media-list endpoint
  v1/media.yaml
Labels: API

#1141 Build: Add the Blubber config file
  .pipeline/blubber.yaml
Labels: enhancement, tests

#1155 Release v1.0.0
  package.json
Labels: dependency update, release
