Repository wikimedia/restbase, pull requests merged in 2019-04, with the labels that each got.

#1109 /edits/per-page endpoint throttling limit is now 5
  v1/metrics.yaml
Labels: API, technical debt

#1110 Fix spacing in v1/recommend.yaml
  v1/recommend.yaml
Labels: API, bug

#1111 Remove optional parameters in sys/
  sys/key_rev_value.yaml
  sys/mobileapps.yaml
  sys/multi_content_bucket.yaml
  sys/page_revisions.yaml
  sys/parsoid.yaml
  sys/post_data.yaml
  test/test_module.yaml
  v1/content.yaml
  v1/mobileapps.yaml
  v1/transform-global.yaml
  v1/transform.yaml
Labels: hygiene, technical debt

#1113 Update metrics docs after AQS patch
  v1/metrics.yaml
Labels: API, hygiene

#1114 Bump service-runner to v2.6.17
  package.json
Labels: dependency update

#1115 Remove listings endpoints from buckets.
  config.example.wikimedia.yaml
  sys/key_rev_value.js
  sys/key_rev_value.yaml
  sys/key_value.js
  sys/key_value.yaml
  sys/multi_content_bucket.js
  sys/multi_content_bucket.yaml
  sys/parsoid.js
  sys/parsoid.yaml
  test/features/buckets/key_value_bucket.js
  test/features/buckets/revisioned_bucket.js
  test/features/pagecontent/pagecontent.js
  test/features/pagecontent/redirects.js
  v1/content.yaml
Labels: hygiene, technical debt

#1116 Prepare key_value bucket for RESTBase split
  .travis.yml
  config.example.wikimedia.yaml
  sys/key_value.js
  sys/key_value.yaml
  sys/mathoid.js
  sys/post_data.js
  test/features/buckets/key_value_bucket.js
  test/features/router/handlerTemplate.js
  test/features/specification/monitoring.js
  test/test_module.yaml
  v1/definition.yaml
  v1/summary.yaml
  v1/summary_new.yaml
Labels: enhancement, technical debt

#1119 Mathoid: Set `x-store-content-type` for check results
  sys/mathoid.js
Labels: hygiene

#1121 Switch stashing to key_value with fallback
  sys/parsoid.js
  test/features/parsoid/transform.js
  v1/content.yaml
Labels: config change, enhancement

#1122 Update HTML content type profile to v2.1.0 in the spec
  v1/content.yaml
  v1/transform.yaml
Labels: bug, technical debt

#1123 [Temp] Log all requests for Parsoid sections
  sys/parsoid.js
Labels: API

#1124 Parsoid: Remove stashing fall-back
  sys/parsoid.js
Labels: technical debt

#1127 Changed Oracle JRE for OpenJDK JRE
  .travis.yml
Labels: tests
