Repository wikimedia/restbase, pull requests merged in 2019-10, with the labels that each got.

#1189 Update hyperswitch to v0.13.0; release v1.1.2
  config.frontend.test.yaml
  package.json
Labels: config change, dependency update, release

#1190 Minor: Parsoid: initialise response headers before using them
  sys/parsoid.js
Labels: bug, technical debt

#1192 [TEMP] Parsoid: Log all VE requests
  sys/parsoid.js
Labels: technical debt

#1191 Add AQS mediarequests endpoints
  v1/metrics.yaml
Labels: API

#1193 Parsoid: Minor tweaks to VE logging
  sys/parsoid.js
Labels: technical debt

#1194 Parsoid: VE logging: Add missing parenthesis
  sys/parsoid.js
Labels: bug, technical debt

#1195 Parsoid: VE logging: The log entry needs either message or msg, not both
  sys/parsoid.js
Labels: technical debt

#1197 Parsoid: VE logging: Enclose the message in `response`
  sys/parsoid.js
Labels: technical debt

#1198 Parsoid: VE logging: Log if etags differ betwen full content and format
  sys/parsoid.js
Labels: technical debt

#1199 Revert "Still use MCS instead of Wikifeeds"
  projects/v1/wikimedia.wmf.yaml
  projects/v1/wikipedia.wmf.yaml
  test/features/feed.js
Labels: config change, enhancement

#1200 Parsoid: Use the ETag's revid to stash the content under
  sys/parsoid.js
Labels: bug, technical debt

#1201 Parsoid: If a stash can't be found, retry with undefined as the revid
  sys/parsoid.js
Labels: technical debt

#1202 Parsoid: Remove the temporary fetching of undef rev and VE logging
  sys/parsoid.js
Labels: technical debt

#1203 Release v1.1.3
  package.json
Labels: release

#1205 Parsoid: Remove now-useless `getFormatAndLog()`
  sys/parsoid.js
Labels: technical debt

#1206 PCS: Do not use storage for /page/metadata; release v1.1.4
  package.json
  projects/v1/wikipedia.wmf.yaml
  projects/v1/wikivoyage.wmf.yaml
  projects/v1/wiktionary.wmf.yaml
  v1/pcs/metadata.yaml
Labels: hygiene, release, technical debt

#1208 Parsoid: Stash: Honour our own ETag when retrieving the stash
  sys/parsoid.js
Labels: API, bug, technical debt

#1209 Add top mediarequests endpoint to metrics
  v1/metrics.yaml
Labels: API

#1210 Parsoid: Shim content-language and vary headers only for the PHP variant
  lib/parsoid.js
  sys/parsoid-php.js
Labels: API, hygiene, technical debt
