Repository wikimedia/restbase, pull requests merged in 2019-08, with the labels that each got.

#1175 Replace deprected `new Buffer` with `Buffer.alloc`.
  sys/mathoid.js
  test/features/buckets/key_value_bucket.js
Labels: technical debt

#1164 Expose fronted RB on 7231 and backend RB on 7233
  config.backend.test.yaml
  config.frontend.test.yaml
  config.fullstack.test.yaml
  package.json
Labels: hygiene, technical debt

#1176 Dep updates
  maintenance/generate-wikimedia-domain-config.js
  package.json
  v1/citoid.js
  v1/pcs/stored_endpoint.js
Labels: dependency update

#1178 Release v1.1.0
  package.json
Labels: release
