Repository wikimedia/restbase, pull requests merged in 2019-09, with the labels that each got.

#1180 Simplify config.example.yaml to avoif using projects
  config.example.yaml
  projects/example.yaml
Labels: technical debt

#1181 MCS: Stop using storage for wiktionary definitions
  v1/definition.yaml
Labels: API, technical debt

#1183 Use debian:stretch as the base image; release v1.1.1
  package.json
Labels: dependency update, release

#1185 Parsoid: Remove the TID suffix, if present
  lib/mwUtil.js
  sys/parsoid.js
Labels: bug

#1186 Still use MCS instead of Wikifeeds
  projects/v1/wikimedia.wmf.yaml
  projects/v1/wikipedia.wmf.yaml
  test/features/feed.js
Labels: technical debt

#1187 Remove the debian/ directory
  debian/README
  debian/changelog
  debian/compat
  debian/config.yaml.example
  debian/control
  debian/copyright
  debian/docs
  debian/gbp.conf
  debian/restbase.default
  debian/restbase.init
  debian/restbase.install
  debian/restbase.logrotate
  debian/restbase.postinst
  debian/restbase.postrm
  debian/rules
  debian/settings.yaml
Labels: hygiene, technical debt
