Repository wikimedia/restbase, pull requests merged in 2019-12, with the labels that each got.

#1221 Parsoid: Proxy: Split fall-back and mirror request cloning
  sys/parsoid.js
Labels: bug

#1222 Parsoid: Proxy: Do not provide a fall-back for lint
  sys/parsoid.js
Labels: bug

#1223 TEMP: Parsoid: Proxy: Send all html2html reqs to JS and ignore the variant header
  sys/parsoid.js
Labels: technical debt

#1224 TEMP: Parsoid: Proxy: Always send html2html to JS but mirror to PHP
  sys/parsoid.js
Labels: technical debt

#1225 Tests: Fix redirect-to-commons test
  test/features/pagecontent/redirects.js
Labels: tests

#1226 Language variants: Use the page title when calling Parsoid
  lib/language_variants_filter.js
Labels: enhancement, hygiene

#1228 Parsoid: Proxy: Send 6% of html2html traffic to Parsoid/PHP
  sys/parsoid.js
Labels: technical debt

#1231 Send lint request to Parsoid/PHP
  sys/parsoid.js
Labels: technical debt

#1233 Parsoid: Proxy: Mirror all html2html requests to PHP
  sys/parsoid.js
Labels: technical debt
